### ISSUE TITLE
Modify Data Management

### ISSUE THREAD

**Issue by shannonrankin** [SAEL-SWFSC/SAEL-lab-manual#10]
Kourtney-- Can you modify the SAEL Lab Manual so that the Data Management Pages reflect the new information provided in the Data Analysis repo?

FWIW-- the Data Analysis will be specific to ADRIFT (at least for now) and we will update the Lab Manual in the future. 
I'm still figuring out how I want to approach that with the shift in platforms (where nearly everything will change). 

But for now, if you can ensure that the lab manual is as updated as possible, that would be great (since it may be viewed a LOT next week!. Thanks!

**Comment by Kourtney-Burger** [comment]
Yeah I can work on that, I can also update the analysis section! Do you want something similar to the hardware methods section, where we have an [ADRIFT specific page](https://sael-swfsc.github.io/SAEL-lab-manual/content/Hardware_ADRIFT.html) that links to the main ADRIFT field methods website? I know it can be annoying to click around to different places but I think it might be better this way so if we update something in the data analysis methods it does not need to be changed in two places

**Comment by shannonrankin** [comment]
For most things-- we want to update in one place (only)...  I am actually
deleting the Analysis Methods page (on the Adrift page, it will link to the
analysis repo). So-- ignore that one.

For the Data Methods-- I'm particularly keen, as you are (so far) the only
one to work on Obis, and you/taiki have put together a good approach for
ncei, etc... so I want that to be outlined enough so that they can see our
approach (it could come up). For these, I think it is probably best to have
a summary, and then the basic details, with a link to extended details (the
extremely detailed play by play). Do what you have now-- and we can update
as we go along.
(By June we can make sure this is updated in the Analysis Methods-- then I
think I will change that Repo to the Adrift Analysis Methods, so at that
point it will stay static as an archive).....

Does that make sense?

**Comment by Kourtney-Burger** [comment]
Got it! That sounds like a good plan, I will work on updating that
