### ISSUE TITLE
Inventree- Instructions & Forms

### ISSUE THREAD

**Issue by shannonrankin** [SAEL-SWFSC/SAEL-lab-manual#6]
Inventree-

- [ ] Complete information page in SAEL-lab-manual for Inventree (placemarker is there)
- [x] Identify a way for people to change the status of a device in Inventree (perhaps create an Issue template in the SAEL general lab project and have those automatically assigned to Kourtney to make the changes in Inventree?

I've assigned this to Kourtney, but she will work with Taiki (and Shannon) to implement this.

**Comment by Kourtney-Burger** [comment]
No longer using inventree but we have places for people to send equipment changes (google form in inventory and in [inventree github repo](https://github.com/Kourtney-Burger/Inventree/issues/new/choose))
